<a href="https://colab.research.google.com/github/Karim-Ashraf1/ML-Project/blob/main/karim_202202209_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
data = pd.read_csv("mhealth_raw_data.csv")

In [ ]:
encoder = LabelEncoder()

data['subject_encoded'] = encoder.fit_transform(data['subject'])
data.drop(columns=['subject'], inplace=True)

In [ ]:
sample = data.sample(n=15000, random_state=42)

X = sample.drop(columns=['Activity'])
y = sample['Activity']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()

X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)

In [ ]:
def evaluate_model(model, X_test, y_test):
    prediction = model.predict(X_test)

    acc = accuracy_score(y_test, prediction)
    precision = precision_score(y_test, prediction, average='weighted')
    recall = recall_score(y_test, prediction, average='weighted')
    f1 = f1_score(y_test, prediction, average='weighted')
    conf_matrix = confusion_matrix(y_test, prediction)

    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("Confusion Matrix:\n", conf_matrix)

    return acc

#***Knn***

In [ ]:
KNN_Model = KNeighborsClassifier(n_neighbors=3) # 3 is the best choise
KNN_Model.fit(X_train_normalized, y_train)

print("KNN Model Evaluation:")
KNeighborsClassifierAccuracy = evaluate_model(KNN_Model, X_test_normalized, y_test)

cv = cross_val_score(KNN_Model, X_train_normalized, y_train, cv=3, scoring='accuracy')
print(f"Cross Validation: {cv}")

KNN Model Evaluation:
Accuracy: 0.8953
Precision: 0.9019
Recall: 0.8953
F1 Score: 0.8973
Confusion Matrix:
 [[2011   18   28   17   20   17   17   18   23   19    5   11]
 [   6   95    0    0    0    0    0    0    0    0    0    0]
 [  11    0   56    0    0    0    0    0    0    0    0    0]
 [   3    0    0   63    0    0    0    0    0    0    0    0]
 [  10    0    0    0   65    0    0    0    0    0    0    0]
 [   4    0    0    0    0   77    0    0    0    0    0    0]
 [  15    0    0    0    0    0   63    0    0    0    0    0]
 [  16    0    0    0    0    0    2   68    0    0    0    0]
 [  11    0    0    0    0    0    0    0   57    0    0    0]
 [  11    0    0    0    0    0    0    0    0   65    4    1]
 [   9    0    0    0    1    0    0    0    0    6   48    1]
 [   5    0    0    0    0    0    0    0    0    4    1   18]]
Cross Validation: [0.889   0.89725 0.8865 ]


#***LinearRegression***

In [ ]:
lR = LinearRegression()
lR.fit(X_train_normalized, y_train)
y_pred = lR.predict(X_test_normalized)

Mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", Mse)

Mean Squared Error: 8.81773153973896


#***LogisticRegression***

In [ ]:
Lg = LogisticRegression(max_iter=1000)
Lg.fit(X_train_normalized, y_train)

print("Evaluation:")
LogisticAccuracy = evaluate_model(Lg , X_test_normalized, y_test)

cv = cross_val_score(Lg, X_train_normalized, y_train, cv=3, scoring='accuracy')
print(f"Cross Validation: {cv}")

Evaluation:
Accuracy: 0.8130
Precision: 0.7821
Recall: 0.8130
F1 Score: 0.7896
Confusion Matrix:
 [[2024    8   46   22   10   12   12   17   21   13   14    5]
 [ 101    0    0    0    0    0    0    0    0    0    0    0]
 [   1    0   66    0    0    0    0    0    0    0    0    0]
 [   0    0    0   66    0    0    0    0    0    0    0    0]
 [  54    0    0    0   21    0    0    0    0    0    0    0]
 [  28    0    0    0    0   53    0    0    0    0    0    0]
 [  48    0    0    0    0    0   30    0    0    0    0    0]
 [  42    0    0    0    0    0    1   43    0    0    0    0]
 [  15    0    0    0    0    0    0    0   53    0    0    0]
 [  40    0    0    0    0    0    0    0    0   35    6    0]
 [  16    0    0    0    0    0    0    0    0    3   45    1]
 [  13    0    0    0    0    0    0    0    0    0   12    3]]
Cross Validation: [0.8195 0.8145 0.8185]


#***svm***

In [ ]:
svm = SVC(kernel='rbf')
svm.fit(X_train_normalized, y_train)

print("SVM Model Evaluation:")
SVMAccuracy = evaluate_model(svm, X_test_normalized, y_test)

cv_scores = cross_val_score(svm, X_train_normalized, y_train, cv=3, scoring='accuracy')
print(f"Cross Validation: {cv_scores}")

SVM Model Evaluation:
Accuracy: 0.8777
Precision: 0.8837
Recall: 0.8777
F1 Score: 0.8774
Confusion Matrix:
 [[1998   31   46   22   13   14   10   14   25   15    7    9]
 [   0  101    0    0    0    0    0    0    0    0    0    0]
 [   0    0   67    0    0    0    0    0    0    0    0    0]
 [   0    0    0   66    0    0    0    0    0    0    0    0]
 [  37    0    0    0   38    0    0    0    0    0    0    0]
 [  11    0    0    0    0   70    0    0    0    0    0    0]
 [  22    0    0    0    0    0   56    0    0    0    0    0]
 [  30    0    0    0    0    0    0   56    0    0    0    0]
 [  12    0    0    0    0    0    0    0   56    0    0    0]
 [  21    0    0    0    0    0    0    0    0   57    3    0]
 [  10    0    0    0    0    0    0    0    0    2   53    0]
 [  10    0    0    0    0    0    0    0    0    0    3   15]]
Cross Validation: [0.84625 0.861   0.84775]


#***Neural*** Network

In [ ]:
nn_model = Sequential([
    Dense(10, activation='relu', input_shape=(None,32,13)),
    Dense(5, activation='relu'),
    Dense(1, activation='softmax')
])

nn_model.compile(optimizer='adam',
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

nn_model.fit(X_train_normalized, y_train, batch_size=32 ,epochs=100,validation_data=(X_train_normalized, y_train))

y_pred = nn_model.predict(X_test_normalized)
y_pred_classes = np.argmax(y_pred, axis=1)

NeuralNetworkAccuracy = accuracy_score(y_test, y_pred_classes)
precision = precision_score(y_test, y_pred_classes, average='weighted')
recall = recall_score(y_test, y_pred_classes, average='weighted')
f1 = f1_score(y_test, y_pred_classes, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred_classes)

print("Neural Network Model Evaluation:")
print(f"Accuracy: {NeuralNetworkAccuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:\n", conf_matrix)

Epoch 1/100
375/375 [==============================] - 6s 13ms/step - loss: -6.2810 - accuracy: 0.0258 - val_loss: -22.1020 - val_accuracy: 0.0258
Epoch 2/100
375/375 [==============================] - 4s 12ms/step - loss: -88.3809 - accuracy: 0.0258 - val_loss: -193.8532 - val_accuracy: 0.0258
Epoch 3/100
375/375 [==============================] - 2s 6ms/step - loss: -396.6648 - accuracy: 0.0258 - val_loss: -663.2817 - val_accuracy: 0.0258
Epoch 4/100
375/375 [==============================] - 1s 3ms/step - loss: -1048.3988 - accuracy: 0.0258 - val_loss: -1515.7656 - val_accuracy: 0.0258
Epoch 5/100
375/375 [==============================] - 1s 3ms/step - loss: -2136.6899 - accuracy: 0.0258 - val_loss: -2852.7209 - val_accuracy: 0.0258
Epoch 6/100
375/375 [==============================] - 1s 3ms/step - loss: -3715.8101 - accuracy: 0.0258 - val_loss: -4665.5068 - val_accuracy: 0.0258
Epoch 7/100
375/375 [==============================] - 1s 3ms/step - loss: -5798.9766 - accuracy: 0.02

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#***result***

In [ ]:
max_accuracy = max(KNeighborsClassifierAccuracy, SVMAccuracy, NeuralNetworkAccuracy, LogisticAccuracy)

if max_accuracy == KNeighborsClassifierAccuracy:
    print(f"Max Accuracy is {max_accuracy:.4f}, achieved by KNN")
elif max_accuracy == SVMAccuracy:
    print(f"Max Accuracy is {max_accuracy:.4f}, achieved by SVM")
elif max_accuracy == NeuralNetworkAccuracy:
    print(f"Max Accuracy is {max_accuracy:.4f}, achieved by Neural Network")
elif max_accuracy == LogisticAccuracy:
    print(f"Max Accuracy is {max_accuracy:.4f}, achieved by Logistic Reggretion")



Max Accuracy is 0.8953, achieved by KNN
